sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rbiagtan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rbiagtan/react-test npm test

after_success:
  - docker build -t rbiagtan/multi-client ./client
  - docker build -t rbiagtan/multi-nginx ./nginx
  - docker build -t rbiagtan/multi-server ./server
  - docker build -t rbiagtan/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push rbiagtan/multi-client
  - docker push rbiagtan/multi-nginx
  - docker push rbiagtan/multi-server
  - docker push rbiagtan/multi-worker

deploy:
  - provider: elasticbeanstalk
  - region: 'us-west-1'
  - app: 'multi-docker'
  - env: 'MultiDocker-env'
  - bucket_name: 'elasticbeanstalk-us-west-1-986424544712'
  - bucket_path: 'docker-multi'
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY